### ISSUE TITLE
Create `py.typed` marker

### ISSUE THREAD

**Issue by pyhedgehog** [damonlynch/showinfilemanager#5]
https://peps.python.org/pep-0561/
https://github.com/python/typeshed/pull/9313#issuecomment-1334136740

**Comment by damonlynch** [comment]
I'm currently avoiding doing any coding because I am trying to recover from a serious typing injury I developed while coding earlier this year. (I'm dictating this message using a voice recognition program.) Unless you can submit something that solves this issue in its entirety, unfortunately I can't take this on until next year, or possibly even 2024. 🤕
